steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_API_KEY=${_NEXT_PUBLIC_FIREBASE_API_KEY}"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_NEXT_PUBLIC_FIREBASE_PROJECT_ID}"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_APP_ID=${_NEXT_PUBLIC_FIREBASE_APP_ID}"
      - "-t"
      - "${_IMAGE_URI}:$COMMIT_SHA"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_IMAGE_URI}:$COMMIT_SHA"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image"
      - "${_IMAGE_URI}:$COMMIT_SHA"
      - "--region"
      - "${_REGION}"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"

images:
  - "${_IMAGE_URI}:$COMMIT_SHA"

substitutions:
  _SERVICE_NAME: "cold-war-game"
  _REGION: "us-east1"
  _IMAGE_URI: "us-east1-docker.pkg.dev/$PROJECT_ID/cold-war-game/cold-war-game"
  _NEXT_PUBLIC_FIREBASE_API_KEY: ""
  _NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ""
  _NEXT_PUBLIC_FIREBASE_PROJECT_ID: ""
  _NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ""
  _NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ""
  _NEXT_PUBLIC_FIREBASE_APP_ID: ""
